cc_test(
    name = "factorial_test",
    srcs = ["factorial_test.cc"],
    deps = [
        "@googletest//:gtest_main",
        "//lib:factorial",
    ],
)

cc_test(
    name = "gamma_test",
    srcs = ["gamma_test.cc"],
    deps = [
        "@googletest//:gtest_main",
        "//lib:gamma",
    ],
)
