cc_library(
    name = "factorial",
    srcs = ["factorial.cc"],
    hdrs = ["factorial.h"],
    visibility = ["//main:__pkg__", "//test:__pkg__"],
)

cc_library(
    name = "gamma",
    srcs = ["gamma.cc"],
    hdrs = ["gamma.h"],
    visibility = ["//main:__pkg__", "//test:__pkg__"],
)